[package]
name = "quick_keys_rust"
version = "0.1.0"
authors = ["Stuff5 <freezedown@hotmail.com>"]

[dependencies]
lazy_static = "1.0"
text_io = "0.1.7"
serialport = "2.0.0"
enigo = "0.0.11"
gtk = "0.3.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
