[package]
name = "quick_keys_core"
version = "0.1.0"
authors = ["Gregory Norton <gregory.norton@me.com>"]

[dependencies]
enigo = "0.0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serialport = "2.0.0"
